project:
  type: website

website:
  title: "IS415-GAAProj"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Project Components"
        menu: 
          - text: "Project Proposal"
            href: "Project-Components/Project-Proposal.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

